# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mytest import chat_pb2 as mytest_dot_chat__pb2


class ChatStub(object):
    """Service class to be used by the clients
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.join = channel.unary_stream(
                '/example.Chat/join',
                request_serializer=mytest_dot_chat__pb2.Message.SerializeToString,
                response_deserializer=mytest_dot_chat__pb2.Message.FromString,
                )
        self.send = channel.unary_unary(
                '/example.Chat/send',
                request_serializer=mytest_dot_chat__pb2.Message.SerializeToString,
                response_deserializer=mytest_dot_chat__pb2.Message.FromString,
                )


class ChatServicer(object):
    """Service class to be used by the clients
    """

    def join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'join': grpc.unary_stream_rpc_method_handler(
                    servicer.join,
                    request_deserializer=mytest_dot_chat__pb2.Message.FromString,
                    response_serializer=mytest_dot_chat__pb2.Message.SerializeToString,
            ),
            'send': grpc.unary_unary_rpc_method_handler(
                    servicer.send,
                    request_deserializer=mytest_dot_chat__pb2.Message.FromString,
                    response_serializer=mytest_dot_chat__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Chat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chat(object):
    """Service class to be used by the clients
    """

    @staticmethod
    def join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/example.Chat/join',
                                             mytest_dot_chat__pb2.Message.SerializeToString,
                                             mytest_dot_chat__pb2.Message.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Chat/send',
                                            mytest_dot_chat__pb2.Message.SerializeToString,
                                            mytest_dot_chat__pb2.Message.FromString,
                                            options, channel_credentials,
                                            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
