apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: appinfo-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: appinfo
spec:
  hosts:
  - "*"
  gateways:
  - appinfo-gateway
  http:
  - match:
    - uri:
#        prefix: /kiali
        exact: /kiali
    route:
      - destination:
          host: kiali
  - route:
    - destination:
        host: msa-client
        subset: v1
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: msa-client
spec:
  host: msa-client
  subsets:
  - name: v1
    labels:
      version: v1